# Generated by Django 5.2.17 on 2026-08-17 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Extra')),
                ('main_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_for_posts', to='core.file', verbose_name='Main file')),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by_posts', to='projects.post', verbose_name='Related post')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_files', to='core.file', verbose_name='File')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_files', to='projects.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Post file',
                'verbose_name_plural': 'Post files',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='posts', through='projects.PostFile', to='core.file', verbose_name='Files'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('link', models.CharField(max_length=64, unique=True, verbose_name='Link')),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('photo', 'Photo'), ('travel', 'Travel'), ('text', 'Text'), ('text_md', 'Markdown text'), ('door', 'Door'), ('anime', 'Anime'), ('plasticine', 'Plasticine'), ('abandoned', 'Abandoned')], default='post', max_length=16, verbose_name='Post type')),
                ('post_list_type', models.CharField(choices=[('post', 'Post'), ('photo', 'Photo'), ('travel', 'Travel'), ('text', 'Text'), ('text_md', 'Markdown text'), ('door', 'Door'), ('anime', 'Anime'), ('plasticine', 'Plasticine'), ('abandoned', 'Abandoned')], default='post', max_length=16, verbose_name='Post list type')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('status', models.CharField(choices=[('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed')], default='open', max_length=16, verbose_name='Status')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.file', verbose_name='Cover')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='projects.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='projects.tag', verbose_name='Tags'),
        ),
        migrations.AddConstraint(
            model_name='postfile',
            constraint=models.UniqueConstraint(fields=('post', 'file'), name='unique_file_per_post'),
        ),
        migrations.AddConstraint(
            model_name='postfile',
            constraint=models.UniqueConstraint(fields=('post', 'order'), name='unique_file_order_per_post'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='unique_post_number_per_project'),
        ),
    ]
