# Generated by Django 5.2.17 on 2026-08-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='related_post',
        ),
        migrations.AddField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(blank=True, to='projects.post', verbose_name='Related posts'),
        ),
    ]
