# Generated by Django 5.2.17 on 2026-08-12 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_file_options_alter_file_content_alter_file_id_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenttype',
            options={'verbose_name': 'Content type', 'verbose_name_plural': 'Content types'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='code',
            field=models.CharField(max_length=64, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.contenttype', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.file', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=64, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
