# Generated by Django 5.2.17 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_post_related_post_post_related_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="post_list_type",
            field=models.CharField(
                choices=[
                    ("row_card", "Row card"),
                    ("photo_card", "Photo card"),
                    ("label_photo_card", "Labeled photo card"),
                    ("rated_photo_card", "Rated photo card"),
                ],
                default="row_card",
                max_length=16,
                verbose_name="Post list type",
            ),
        ),
    ]
