# Generated by Django 5.2.17 on 2026-08-17 03:20

import apps.core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Original name')),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', editable=False, max_length=16, verbose_name='File type')),
                ('content', models.FileField(upload_to=apps.core.models.file_upload_path, verbose_name='Content')),
                ('preview', models.ImageField(blank=True, editable=False, null=True, upload_to=apps.core.models.preview_upload_path, verbose_name='Preview')),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to=apps.core.models.thumbnail_upload_path, verbose_name='Thumbnail')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
