# Generated by Django 5.2.17 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="original_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Original name",
            ),
        ),
    ]
